name: Test SSH

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Test
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "CONNECTED SUCCESSFULLY"
          pwd
